### ISSUE TITLE
english language summary

### ISSUE THREAD

**Issue by andrisi** [JimmyAndZzZ/hulk#1]
Please provide a bried english summary for your project. Does it implement the server side of the MySQL protocol in Java? Thanks!

**Comment by JimmyAndZzZ** [comment]
I apologize for the delayed response. To simulate communication as a MySQL client using Netty as the communication framework, you can refer to the package information provided by MySQL official.

The protocol package contains specific protocol classes.

The Bootstrap class is the main startup class. It performs various callback processing through actions.

**Comment by andrisi** [comment]
Thanks for the response, but to clarify, I'm looking to implement *server side* MySQL, if possible. Create a service that looks like a MySQL server from the outside. Is this supported?

**Comment by JimmyAndZzZ** [comment]
Sorry, I was mistaken. Actually, what I am simulating is the server-side MySQL protocol. The communication with JDBC can be directly done with Hulk.
